n = input('Digite algo para ser classificado:')
print('O tipo primitivo desse valor é', type(n))
print('É alfanumérico?', n.isalnum())
print('É um número?', n.isnumeric())
print('É alfabético?', n.isalpha())
print('Está maiúsculo?', n.istitle())
print('Está em minúsculas?', n.islower())
print('Está captalizado:', n.isupper())
print('Só tem espaços? ', n.isspace())
